var myString;
var myNum;
var myBool;
var myVal;
var objArray;
myBool = true;
myString = "Hello World";
myNum = 22;
myVal = [5];
objArray = [{ me: 'a' }];
console.log(myVal);
console.log(myBool);
console.log(myNum);
console.log(myString);
