var myString;
var myNum;
var myBool;
var myVal;
var objArray;
var myVoid;
var myNull;
var myUndefined;
myBool = true;
myString = "Hello World";
myNum = 22;
myVal = [5];
objArray = [{ me: 'a' }];
myVoid = null;
myNull = null;
myUndefined = undefined;
console.log(myVal);
console.log(myBool);
console.log(myNum);
console.log(myString);
